### ISSUE TITLE
Problem booking and placing order

### ISSUE THREAD

**Issue by MarioGSandoval** [tirgei/Automart#1]
Hello, Tirgei. 
How are you?
I downloaded your app to learn more about firestore and to learn how to use fragments. The project is great and I started to explore it but I have a doubt...
When I book a test drive or when I place an order, nothing happens in firebase and I cannot see anything like a booking or order in the account where I posted the car/part. 
I see the next errors: 
 `E/PartActivity$makeOrder: RESULTS: Error: could not handle the request`

`E/CarActivity$book: RESULTS: {"booker_id":"RQWcPYHuRtSgR7pkH6Q1czEaGvN2","resultCode":0,"description":"Booking created succesfully","seller":"Mario Sandoval"}`

These are my rules on firebase:
Realtime Database:
`{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null"
  }
}`

Firestore:
`service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write;
    }
  }
}`

How do you solve it? Do you have the same issue? I have not modified the code, I just added the _.json_ archive
I hope you can help me.

**Comment by tirgei** [comment]
> Hello, Tirgei.
> How are you?
> I downloaded your app to learn more about firestore and to learn how to use fragments. The project is great and I started to explore it but I have a doubt...
> When I book a test drive or when I place an order, nothing happens in firebase and I cannot see anything like a booking or order in the account where I posted the car/part.
> I see the next errors:
> `E/PartActivity$makeOrder: RESULTS: Error: could not handle the request`
> 
> `E/CarActivity$book: RESULTS: {"booker_id":"RQWcPYHuRtSgR7pkH6Q1czEaGvN2","resultCode":0,"description":"Booking created succesfully","seller":"Mario Sandoval"}`
> 
> These are my rules on firebase:
> Realtime Database:
> `{ "rules": { ".read": "auth != null", ".write": "auth != null" } }`
> 
> Firestore:
> `service cloud.firestore { match /databases/{database}/documents { match /{document=**} { allow read, write; } } }`
> 
> How do you solve it? Do you have the same issue? I have not modified the code, I just added the _.json_ archive
> I hope you can help me.

Hi Mario.

Glad my project could be of help to you. The app is made up of 2 parts i.e the android app (which should be the one you downloaded) and the Firebase Functions app (which is linked to the project. You can find it [here](https://github.com/tirgei/Automart-Functions). The Firebase Functions app is the one used to handle placing an order and booking a test driver which I presume are the parts giving you a problem.

You can download the Firebase Functions repo and deploy it to your Firebase so as to have the full functionality. 

Incase you need any assistance, please feel free to ask. Thanks.

**Comment by MarioGSandoval** [comment]
Thank you for your support, Tirgei!
I've deployed the function, as you can see in the next image, but I still have the same issue. It's my first time using _functions_, so I don't know if I have to do something else. 

![car](https://user-images.githubusercontent.com/49497989/56904035-151c6600-6a63-11e9-8a00-6d091e71e817.PNG)

Btw, your code is well structured and easily understandable.

**Comment by MarioGSandoval** [comment]
Problem solved. I forgot to change the URL in K.kt

I see that there is a URL for the function _sales report_, can you provide it? Now I'm interested about learning also about _functions_ and I would like to try it.

Best regard,
Mario.

**Comment by tirgei** [comment]
> Btw, your code is well structured and easily understandable.

Thanks

**Comment by tirgei** [comment]
> Problem solved. I forgot to change the URL in K.kt
> 
> I see that there is a URL for the function _sales report_, can you provide it? Now I'm interested about learning also about _functions_ and I would like to try it.
> 
> Best regard,
> Mario.

Hi,

I have pushed the missing `getReports()` function to the [Automart Functions](https://github.com/tirgei/Automart-Functions) repo. You can check it out and test it if it's working as expected.

Yeah you should also learn about Firebase Functions too as they provide a better way of handling functions that you would not want to put in the android app. You can also use it to automatically do stuff like sending notifications to your app users.

Regards,
Tirgei
